
## mio <- Module("R2R", PACKAGE = "RIPOpenCV")
mi <- Module("R2R", PACKAGE = "RIPOpenCV")
## mblur <- Module("Blur", PACKAGE = "RIPOpenCV")
## mfeature <- Module("Feature", PACKAGE = "RIPOpenCV")
## mmorph <- Module("Morph", PACKAGE = "RIPOpenCV")
## mgeo <- Module("geoTrans", PACKAGE = "RIPOpenCV")
## mhist <- Module("hist", PACKAGE = "RIPOpenCV")
## mpyr <- Module("pyr", PACKAGE = "RIPOpenCV")
## mrla <- Module("rla", PACKAGE = "RIPOpenCV")
## mdft <- Module("Dft", PACKAGE = "RIPOpenCV")
## mconv2direct <- Module("conv2direct", PACKAGE = "RIPOpenCV")
## mrobsp <- Module("robsp", PACKAGE = "RIPOpenCV")
## munsharpMask <- Module("unsharpMask", PACKAGE = "RIPOpenCV")
## mdenoiseEdge <- Module("denoiseEdge", PACKAGE = "RIPOpenCV")
## mdenoise <- Module("denoise", PACKAGE = "RIPOpenCV")
mvideo <- Module("video", PACKAGE = "RIPOpenCV")
